name: Publish package to GitHub Packages

on:
  release:
    types: [published]
jobs:
   publish-gpr:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with:
           node-version: '16.x'
           registry-url: https://npm.pkg.github.com/
           scope: '@notreeceharris'
       - uses: jgierer12/npm-auth-gpr@v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - run: npm ci
       - run: npm i
       - run: npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

